
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
  pull_request:

defaults:
  run:
    shell: bash


jobs:
  test:
    defaults:
      run:
        working-directory: backend
        
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.7' # This specific version was used for testing
  
    - name: Run TEST
      run: ./mvnw test

  infra:
    defaults:
      run:
        working-directory: infra
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    # If we can not deploy the changes we can not allow this to be in master
    - name: Terraform Plan
      run: terraform plan

    # Only apply if it's master
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
